# sqlgit_config.yml


#
# application mode
#

readonly_global: false                    # high-level readonly parameter. For low-level readonly check the xsdb-parameters.

readonly_guest_enable: true               # can the app be accessed in read-only mode without sign-in ?

registration_enable: true                 # is the registration-page available ?
registration_with_invitation_code: true   # does a new user need an invitation-code for registring ?
registration_with_captcha: true           # is there a captcha in the registaration-page ?

create_new_user: true                     # enable registered user to create new users



#
# web server front
#

http:
  enable: true
  port: 8081
  hostname: "localhost"   # localhost/INADDR_LOOPBACK (127.0.0.1), any/INADDR_ANY (0.0.0.0)

https:
  enable: true
  port: 8082
  hostname: "0.0.0.0"     # localhost/INADDR_LOOPBACK (127.0.0.1), any/INADDR_ANY (0.0.0.0)
  key: "./ssl_sqlgit.key"
  cert: "./ssl_sqlgit.crt"


#
# backend databases
#

xsdb_main:
  path: "./xsdb/xsdb_sqlgit_main"
  name: "xsdb_sqlgit_main"
  readonly: false
  remotes:
  - url: git@github.com:charlyoleg/xsdb_sqlgit_main1.git
    branch: master
  - url: git@github.com:charlyoleg/xsdb_sqlgit_main2.git
    branch: main
  - url: git@github.com:charlyoleg/xsdb_sqlgit_main3.git
    branch: backup

xsdb_secondary:
  path: "./xsdb/xsdb_centaure"
  name: "centaure"
  readonly: false
  remotes:
  - url: git@github.com:charlyoleg/xsdb_centaure1.git
    branch: master
  - url: git@github.com:charlyoleg/xsdb_centaure2.git
    branch: master


